server:
  port: 8010

spring:
  application:
    name: mall-auto

  main:
    allow-circular-references: true

  datasource:
    # 数据库
    url: jdbc:mysql://127.0.0.1:3306/tk4?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B4
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 5
    min-idle: 5
    max-active: 10
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    mapper-locations: classpath*:mapper/*.xml

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  type-enums-package: com.auto.mall.enums
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mall:
  order:
    api: http://127.0.0.1:8081/api/order-local!submit.action

  redis:
    host: redis://127.0.0.1:6379
    password:
